CREATE TABLE IF NOT EXISTS cobweb.`TOPIC_SCHEMA` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `TAG` varchar(10) NOT NULL,
  `DATA_SOURCE` varchar(100) NOT NULL,
  `CATALOG` varchar(100) NOT NULL,
  `TABLE` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TOPIC_SCHEMA_UN` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TOPIC SCHEMA';